name: stew ci
description: Installs stew from the current source, and use it to test itself.

inputs:
  python-version:
    description: The python version
    required: true
  poetry-version:
    description: The poetry version constraint
    required: false
    default: ""

runs:
  using: 'composite'

  steps:
    - name: stew-plugin
      shell: bash
      run: pipx inject poetry .

    - name: Ensure correct python version
      shell: bash
      run: poetry env use python

    - name: Run stew ci
      shell: bash
      run: poetry stew ci coveo-stew --exact-match
