name: setup python and tools

inputs:
  python-version:
    description: The python version
    required: true
  poetry-version:
    description: The poetry version constraint
    required: false
    default: ""

runs:
  using: 'composite'

  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pipx
      shell: bash
      run: python -m pip install --user pipx

    - name: Ensure pipx uses the correct Python
      shell: bash
      run: python -m pipx ensurepath

    - name: Install poetry
      shell: bash
      run: pipx install "poetry${{ inputs.poetry-version }}"

    - name: poetry-export
      shell: bash
      run: pipx inject poetry poetry-plugin-export
