name: stew ci
description: Launch "stew ci" on a python project

inputs:

  project-name:
    description: The project name, from the pyproject.toml file.
    required: true

  python-version:
    description: The python version number, such as "3.10". See `actions/setup-python` for documentation.
    required: true

  poetry-version:
    description: The pip constraint when installing poetry.
    required: false
    default: "<2.0.0"

  coveo-stew-version:
    description: The pip constraint when installing coveo-stew.
    required: false
    default: "<4"

  run-stew:
    description: If not "true", `stew ci` will not be ran. This is a shortcut to checkout/setup-python/poetry/stew without running it.
    required: false
    default: "true"

  install-python:
    description: Can be set to false to skip installing python.
    required: false
    default: "true"

  python-exec:
    description: The name of the python executable
    required: false
    default: "python"


runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      if: inputs.install-python == 'true'
      with:
        python-version: ${{ inputs.python-version }}

    - name: Prepare pipx path
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Upgrade python tools and install pipx
      shell: bash
      env:
        PYTHON_EXEC: ${{ inputs.python-exec }}
      run: $PYTHON_EXEC -m pip install --upgrade pip wheel setuptools pipx --user --disable-pip-version-check

    - name: poetry and stew
      shell: bash
      env:
        POETRY_VERSION: ${{ inputs.poetry-version }}
        COVEO_STEW_VERSION: ${{ inputs.coveo-stew-version }}
        PYTHON_EXEC: ${{ inputs.python-exec }}

      run: |
        $PYTHON_EXEC -m pipx install "poetry$POETRY_VERSION"
        $PYTHON_EXEC -m pipx inject poetry poetry-plugin-export
        $PYTHON_EXEC -m pipx install "coveo-stew$COVEO_STEW_VERSION"

    - name: Run stew ci
      if: inputs.run-stew == 'true'
      shell: bash
      env:
        PROJECT_NAME: ${{ inputs.project-name }}
      run: stew ci $PROJECT_NAME --exact-match
