[tool.poetry]
name = "coveo-stew"
version = "3.1.0"
description = "Opinionated python packaging and development utilities"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/coveo/stew"
authors = ["Jonathan Piché <tools@coveo.com>"]

packages = [
    { include = "coveo_stew/**/*" },
]


[tool.poetry.dependencies]
python = ">3.9,<4"
click = "^8.1.0"
coveo-functools = "^2.0.0"
coveo-itertools = "^2.0.0"
coveo-systools = "^2.0.13"
coveo-styles = "^2.1.2"
junit-xml = "*"
packaging = "*"
setuptools = "^78.0.0"
toml = "*"
tomlkit = "*"
importlib-resources = "^6.1.1"


[tool.poetry.group.dev.dependencies]
black = "24.10"
coveo-testing = "^2.0.0"
flake8 = "^7.0.0"
isort = "*"
mypy = "1.12"
pytest = "*"
types-setuptools = "*"
types-toml = "*"


[tool.poetry.scripts]
stew = "coveo_stew.commands:stew"

[tool.stew]
build-without-hashes = true

[tool.stew.ci]
pytest = true
offline-build = true
black = true


[tool.stew.ci.custom-runners]
flake8 = { check-args = "--ignore=E203,E501,E701,E704,W503" }

[tool.stew.ci.custom-runners.isort]
check-args = ["--check", "--profile", "black", "."]
autofix-args = ["--profile", "black", "."]


[tool.black]
line-length = 100


[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
