[project]
name = "mock-pyproject-dependency"
version = "0.2.4"
description = "mocked dependency for pyproject mock"
authors = [
    { name = "Jonathan Piché", email = "tools@coveo.com" },
]

requires-python = ">=3.9,<4"

dependencies = [
    "requests <=2.26",
    "black",
]


[tool.stew.build-dependencies]
setuptools-scm = "*"


[build-system]
requires = ["poetry_core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
