[tool.poetry]
name = "mock-poetry-groups"
version = "0.1.1"
description = "an internal mock for stew's tests"
authors = ["Jonathan piché <tools@coveo.com>"]


[tool.poetry.dependencies]
python = ">=3.9,<4"

requests = "*"


[tool.poetry.group.extra.dependencies]
black = "*"


[tool.poetry.group.dev.dependencies]
mypy = "*"


[build-system]
requires = ["poetry_core>=2.0.0"]
build-backend = "poetry.core.masonry.api"