[project]
name = "mock-poetry-groups"
version = "0.1.1"
description = "an internal mock for stew's tests"
authors = [
    { name = "Jonathan Piché", email = "<tools@coveo.com>" }
]

requires-python = ">=3.9,<4"

dependencies = [
    "requests"
]


[tool.poetry.group.extra.dependencies]
black = "*"


[tool.poetry.group.dev.dependencies]
mypy = "*"


[build-system]
requires = ["poetry_core>=2.0.0"]
build-backend = "poetry.core.masonry.api"